### ISSUE TITLE
Incomplete Requirements List

### ISSUE THREAD

**Issue by TravisBernard** [richdynamix/magestead#101]
I'm installing on Windows 7 Pro with PHP 7.0.* installed stand alone without apache or IIS.

When I ran `magestead new projectname` I had an error related to GREP being missing.  To fix it I installed: http://gnuwin32.sourceforge.net/packages/grep.htm and added it to my PATH.

After passing that error I had an error about CURL_INIT not being found, I didn't have CURL enabled in php.ini.  I know this is defacto for most setups but a raw PHP install on windows will not have curl enabled.

After fixing those two things everything else seems to have gone fine.

**Comment by DonavanHeng** [comment]
> Mac or Linux (sorry no windows support yet)

The list should be updated to reflect additional steps for Windows, but if I remember correctly @richdynamix doesn't have any WIN environment to test on.

**Comment by TravisBernard** [comment]
Oh, no kidding, totally missed that.  I think I almost have it working, but i keep hitting weird errors and I'm not familiar enough with Vagrant to fix them.  That's too bad.

**Comment by richdynamix** [comment]
Please feel free to submit a PR to support Windows :)
