### ISSUE TITLE
local.xml is not generating

### ISSUE THREAD

**Issue by CallumBrankin** [richdynamix/magestead#103]
> Warning: file_get_contents(C:\Users\user\Documents\v/m/public/app/etc/local.xml): failed to open stream: No such file or directory in C:\Users\user\AppData\Roaming\Composer\vendor\richdynamix\magestead\src\Magestead\In                                      stallers\MagentoProject.php on line 214

>   [Exception]
>   String could not be parsed as XML

The error above occurs because it's trying to find local.xml but it does not exist. 

I'm on Windows 10.

**Comment by richdynamix** [comment]
Please refer to the docs where Windows OS is not yet supported. Please feel free to submit a PR :)

**Comment by ghost** [comment]
I'm running on OS X and still getting the above issue.

**Comment by tylers-username** [comment]
I haven't looked at the code that references the local.xml. However, this looks like a simple case of the wrong directory separators being used. I don't have time to submit a pull request but you might hack around with replacing any hard coded '/' with `DIRECTORY_SEPARATOR`.
