### ISSUE TITLE
NFS Default?

### ISSUE THREAD

**Issue by dccampbell** [richdynamix/magestead#14]
Currently the folder sync is configured to use NFS by default, but NFS is unfortunately incompatible with Windows hosts and encrypted drives. Like Vagrant itself, the default should probably be left alone for better compatibility, with an easy way to toggle it on for those that can utilize the performance boost.

**Comment by richdynamix** [comment]
I agree the default should be the standard synced folders however the performance is just not good enough to run Magento development at all and I wanted Magestead to be performant from the start.

Unfortunately I do not have a windows machine to test this out with SMB or RSYNC so I just kept the default to NFS. You are free to create a PR with updates if you can test the SMB and RSYNC. Should be able to set in the `Magestead.yaml` file the config options for folder syncing.

**Comment by dccampbell** [comment]
It looks like currently there's not really a way to specify the synced folder settings without editing Magestead.rb, I think that's possibly the bigger issue right now.

Without going all the way to Homestead's level of folder management, maybe an intermediate solution would look something like:

``` ruby
mount_type = settings["mount_type"]
mount_opts = settings["mount_opts"]

mount_type ||= "nfs"
if (mount_type == "nfs")
    mount_opts ||= ["dmode=777","fmode=666"]
end

config.vm.synced_folder ".", "/vagrant", type: mount_type , mount_options: mount_opts
```

I know absolutely zero Ruby so I admit I'm kinda guessing at the syntax there, but I _think_ that should allow modification of type and options in the YAML.

**Comment by richdynamix** [comment]
Just released a new version that uses a similar approach you have. It's pretty much a copy of Homestead's settings but cut down for a per project rather than per folder. Hope this helps :)

**Comment by richdynamix** [comment]
@JorenRapini This is issue was directly related to Magestead V1 where there was the ability to use SMB for folder sync on Windows. Unfortunately Magestead 2 does not support windows at present as the entire infrastructure has changed and I do not have a windows machine to test on.

Feel free to update where required and submit a PR :)
