### ISSUE TITLE
Vagrant up an error occured while downloading remote file

### ISSUE THREAD

**Issue by Truemedia** [richdynamix/magestead#16]

**Comment by Truemedia** [comment]
This seems to happen to me immediately when running vagrant up. I have an internet connection and not sure why this would occur.

**Comment by richdynamix** [comment]
I have just added a fix where it was referencing the wrong box. Please pull latest master branch and try again.

**Comment by Truemedia** [comment]
Thanks I get past this part now :), will close this.
