### ISSUE TITLE
Issue sharing folders NFS

### ISSUE THREAD

**Issue by Truemedia** [richdynamix/magestead#18]
During the vagrant up procedure I now get an issue when it gets to this part of the task:

==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'actimeo=1' 192.168.47.1:'/home/user/Documents/vagrant/magestead' /vagrant

Stdout from the command:

Stderr from the command:

mount.nfs: access denied by server while mounting 192.168.47.1:/home/user/Documents/vagrant/magestead

Not sure if this is an issue directly linked to my computer, or if this is a common vagrant issue.

**Comment by richdynamix** [comment]
This is a direct issue between vagrant and your machine. Are you using the latest version of vagrant? There have been known issue with NFS in older versions of vagrant on different operating systems.

This might be able to help you, it seems to be connected to several other related issues across multiple environments https://github.com/mitchellh/vagrant/issues/1941

**Comment by Truemedia** [comment]
Thanks ill take a look at that issue and try the other solutions. I did see something that was definitely causing me issues in that my home directory was encrypted (an option I had accidentally ticked on installing ubuntu). My home directory is now unencrypted but the issue still persists.

I am on pretty recent versions of ubuntu, vagrant, and virtualbox because I have set all those up on a brand new harddrive just a few weeks ago. The exact versions I have are ubuntu 15.10, virtualbox 5.0.4, and vagrant 1.7.4

**Comment by Truemedia** [comment]
Fixed it! after trying every command on that page for some reason the very last one worked.

VAGRANT_USE_VBOXFS=true vagrant up

Thought that option was already specified somewhere, but it works. Only issue is I get an nginx 500 error when I visit http://192.168.47.10/ will open that in another issue thanks :)
