### ISSUE TITLE
JS and CSS not loading

### ISSUE THREAD

**Issue by ercanertan** [richdynamix/magestead#21]
I have completed installing progress but css and js seems like not loading on front and back end side.I was trying to add  
chown -R vagrant media
chmod -R o+w media
but I couldn't figure out how to access media directory from "vagrant ssh"
Any Solution?

**Comment by richdynamix** [comment]
Hi,

Which framework did you bootstrap? By default you shouldn't need to fix permissions on the box as these are done at time of provisioning. If you `vagrant ssh` into the box you should be able to access your project files under `/vagrant/magento`.

Should you need to change permissions you should should try `sudo`.

**Comment by richdynamix** [comment]
Closing as unable to replicate
