### ISSUE TITLE
php & nginx permissions

### ISSUE THREAD

**Issue by cannycookie** [richdynamix/magestead#22]
nginx and php session folders have wrong permissions 
Added this to startup script:-

```
chown -R vagrant:vagrant /var/lib/nginx
chown -R vagrant:vagrant /var/lib/php/session
```

**Comment by richdynamix** [comment]
Thanks for the update Lee. I will look at adding this directly to the box :+1: Will keep this issue open as a reminder.

**Comment by richdynamix** [comment]
Fixed in https://github.com/richdynamix/magestead/releases/tag/1.5
