### ISSUE TITLE
php.ini upload_max_filesize only 2Mb  - scripted update

### ISSUE THREAD

**Issue by cannycookie** [richdynamix/magestead#23]
Also useful if you want to script the updating of php.ini

```
upload_max_filesize="=64M"
post_max_size="=64M"

for key in upload_max_filesize post_max_size
do
 sed -i "s/^\($key\).*/\1 $(eval echo \${$key})/" /etc/php.ini
done
```

**Comment by richdynamix** [comment]
Very useful indeed. I think it would be good to add this as part of the provisioning. Allowing the users to set values like this in the YAML file would be a great advantage. Noting as enhancement. :+1:

**Comment by cannycookie** [comment]
Ooh and another config update for the nginx server conf.  Unable to upload files without this:-

```
client_max_body_size 64M;
```

**Comment by richdynamix** [comment]
Fixed in https://github.com/richdynamix/magestead/releases/tag/1.5
