### ISSUE TITLE
Server status messages are in German

### ISSUE THREAD

**Issue by cannycookie** [richdynamix/magestead#24]
Any idea how to switch error and status messages back to English?

The default language seems to be English but getting random messages in German.

**Comment by cannycookie** [comment]
ha! found it edit:-

`/etc/sysconfig/i18n`

change to en_GB

**Comment by richdynamix** [comment]
This has been a serious bug of mine for a while. I had no idea why errors were in German. I will make this change in the box and add as new version. :+1:

**Comment by cannycookie** [comment]
Happy to help :-)

**Comment by richdynamix** [comment]
Fixed in https://github.com/richdynamix/magestead/releases/tag/1.5
