### ISSUE TITLE
lzf.so module required for mage

### ISSUE THREAD

**Issue by cannycookie** [richdynamix/magestead#25]
Just found this php module also required by Magento

http://www.webmaster2020.com/guides/lzf_php.php

**Comment by richdynamix** [comment]
This isn't a hard requirement, rather a nice to have unless you have other modules that depend on it. The box has the bare minimal requirements to run Magento, Magento 2, Laravel & Symfony.

You could use the installed n98-magerun tool to check the box - 

`$ magerun sys:check`

You should see something like - 

```
✔ Required PHP Module simplexml found.
✔ Required PHP Module mcrypt found.
✔ Required PHP Module hash found.
✔ Required PHP Module gd found.
✔ Required PHP Module dom found.
✔ Required PHP Module iconv found.
✔ Required PHP Module curl found.
✔ Required PHP Module soap found.
✔ Required PHP Module pdo found.
✔ Required PHP Module pdo_mysql found.
```

**Comment by cannycookie** [comment]
Yeah I know, just leaving that for anyone else who hit upon the issue.

Turns out lzf_compress function is  only used by redis cache (but other compression options can be used) so is not required by default mage install.

**Comment by richdynamix** [comment]
Closing this ticket as this is addressed in V2 of Magestead
