### ISSUE TITLE
Real slow on OSX El Capitan / Magento 2 Bootstrapped

### ISSUE THREAD

**Issue by andypimlett** [richdynamix/magestead#27]
Hey,

Setup and provisioning went well. etc/hosts modified and everything resolving but site performance is painfully slow for frontend and admin.

Is there something I am missing?

**Comment by richdynamix** [comment]
Hey Andy,

Has the caches been turned on? Performance of Magento 2 on Magestead is still slightly off. I have been working on a new version of Magestead that uses REDIS for sessions and FPC. Something has increased the performance by quite a bit.

Version 2 beta should be available soon. Watch the repo to get alerts.

**Comment by andypimlett** [comment]
No cacheing yet, just literally provisioned and browsed as is.
Will look out for the update, thx.

**Comment by richdynamix** [comment]
Initial performance issues have now been addressed in https://github.com/richdynamix/magestead/pull/32.
