### ISSUE TITLE
Incorrect password in magento

### ISSUE THREAD

**Issue by TomFoyster** [richdynamix/magestead#29]
I apologise if I've missed something during setup that's caused this problem, however I've found;

In create-mysql.sh the database is accessed and created with user `root` and password `vagrant`. Elsewhere though, in magento-bootstrap.sh and magento-local.xml the values are `root` and `root`.

I can only access the DB using `root` and `vagrant` also. 

Is this an issue?

**Comment by richdynamix** [comment]
I think you may have found a few typos. It's possible during my development I may have used the `root`, `root` combination however I do believe it should be `root`, `vagrant`. 

Have you tried changing the credentials before running an initial provision? If there is no issues I will update immediately.

**Comment by TomFoyster** [comment]
Hi Steven, 

Yup, changed the passwords to match `root`, `vagrant` and the installation worked fine. 

I'm having some other issues around using modman and Magestead, would be good to chat about them briefly away from here if possible?

Thanks Steven.

**Comment by richdynamix** [comment]
Fixed in https://github.com/richdynamix/magestead/pull/30
