### ISSUE TITLE
Magento 1 PHP 7 Support

### ISSUE THREAD

**Issue by inluxc** [richdynamix/magestead#43]
Can we add php7 magento support by adding https://github.com/Inchoo/Inchoo_PHP7 extention.

**Comment by richdynamix** [comment]
Thanks for the request. 

I was avoiding this for the time being as the the extension doesn't make it 100% compatible. There are a few known issues under the Notes section.

That being said I am more than happy to add it in and build the Magento project with the this extension added, however I will need to update the docs to explain the caveats to reduce of issues raised.
