### ISSUE TITLE
301 Moved Permanently prepended

### ISSUE THREAD

**Issue by veilig2000** [richdynamix/magestead#48]
I setup on a Mac using apache as my webserver.  Everything is working fine, but when I load any page I have a nginx document prepended before my magento page?  

it says 
#301 Moved Permanently

nginx/1.9.11

I looked at the headers and verified I'm in fact using apache like I expected when I ran the magestead setup

```
Server:Apache/2.4.20 (Ubuntu)
```

I'm not sure where nginx is coming into play?

**Comment by richdynamix** [comment]
Would you be able to share the contents of your `magestead.yaml` file so I can try and reproduce?

I have not had any issues like this before, very strange. Was this on a first time run or did you try and run magestead setup over an existing project?
