### ISSUE TITLE
Magestead install fails every time

### ISSUE THREAD

**Issue by joshuabromero** [richdynamix/magestead#49]
Recently Magestead has started failing when trying to create a new instance of Magento (1 or 2). I've included the output below. This occurs right after Behat gets installed (in the case of Magento 2)

```
/usr/local/rvm/scripts/extras/bash_zsh_support/chpwd/function.sh: line 5: cd: /var/www/public: No such file or directory
chmod: cannot access ‘bin/behat’: No such file or directory
bash: bin/behat: No such file or directory
Setting Permissions
/usr/local/rvm/scripts/extras/bash_zsh_support/chpwd/function.sh: line 5: cd: /var/www/public: No such file or directory
Folder Permissions Set
/usr/local/rvm/scripts/extras/bash_zsh_support/chpwd/function.sh: line 5: cd: /var/www/public: No such file or directory
File Permissions Set
/usr/local/rvm/scripts/extras/bash_zsh_support/chpwd/function.sh: line 5: cd: /var/www/public: No such file or directory
chmod: cannot access ‘bin/magento’: No such file or directory
chmod: cannot access ‘bin/phpspec’: No such file or directory
chmod: cannot access ‘bin/behat’: No such file or directory
bin/magento Permissions Set
Installing Magento 2 Software
/usr/local/rvm/scripts/extras/bash_zsh_support/chpwd/function.sh: line 5: cd: /var/www/public: No such     file or directory
bash: bin/magento: No such file or directory
Reindexing Tables
/usr/local/rvm/scripts/extras/bash_zsh_support/chpwd/function.sh: line 5: cd: /var/www/public: No such file or directory
bash: bin/magento: No such file or directory
Flushing All Cache
/usr/local/rvm/scripts/extras/bash_zsh_support/chpwd/function.sh: line 5: cd: /var/www/public: No such file or directory
bash: bin/magento: No such file or directory
Configuring Redis Cache
PHP Warning:  include(/Users/joshuablake/Sites/mage2var/magento2/public/app/etc/env.php): failed to   open stream: No such file or directory in    /Users/joshuablake/.composer/vendor/richdynamix/magestead/src/Magestead/Installers/Magento2Project.php on line 137

Warning: include(/Users/joshuablake/Sites/mage2var/magento2/public/app/etc/env.php): failed to open stream: No such file or directory in /Users/joshuablake/.composer/vendor/richdynamix/magestead/src/Magestead/Installers/Magento2Project.php on line 137
PHP Warning:  include(): Failed opening '/Users/joshuablake/Sites/mage2var/magento2/public/app/etc/env.php' for inclusion (include_path='.:') in /Users/joshuablake/.composer/vendor/richdynamix/magestead/src/Magestead/Installers/Magento2Project.php on line 137

Warning: include(): Failed opening '/Users/joshuablake/Sites/mage2var/magento2/public/app/etc/env.php' for inclusion (include_path='.:') in /Users/joshuablake/.composer/vendor/richdynamix/magestead/src/Magestead/Installers/Magento2Project.php on line 137
```

**Comment by richdynamix** [comment]
Can you paste in the contents of your magestead.yaml file?

When you say it fails every time, are you trying to install in a fresh, empty folder?

**Comment by joshuabromero** [comment]
I figured out the issue. Had nothing to do with Magestead. Turns out a good
‘ol restart cleared up the issue. I was doing a lot of work with Magestead
and Vagrant trying to learn their in’s and out’s. Thanks for the reply
Steven.

On June 2, 2016 at 2:36:23 AM, Steven Richardson (notifications@github.com)
wrote:

Can you paste in the contents of your magestead.yaml file?

When you say it fails everytime, are you trying to install in a fresh,
empty folder?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/richdynamix/magestead/issues/49#issuecomment-223207779,
or mute the thread
https://github.com/notifications/unsubscribe/APctVrXIM-_jWeBv0K17wAs_tAYdg-1Bks5qHnnngaJpZM4Ir7bT
.

**Comment by richdynamix** [comment]
Excellent. Glad you got it sorted. Hope you find it useful 😁

**Comment by MPietrukowski** [comment]
Hi,
I have this problem but restart is not helping in my case
every was working fine but then I have decided to install vagrant-hostsupdater
and public directory is not present is /var/www/

/usr/local/rvm/scripts/extras/bash_zsh_support/chpwd/function.sh: line 5: cd: /var/www/public: No such file or directory

vagrantfile:
    puphpet: false
    advanced: 'false'
    vm:
        box: richdynamix/magestead-centos65-nginx-php56
        box_url: richdynamix/magestead-centos65-nginx-php56
        hostname: magestead-project4.dev
        memory: '4096'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.44.44
        synced_folder:
            vflsf_uocnhnxzm524:
                sync_type: nfs
magestead:
    apps:
        mba_12345:
            type: magento
            dir: /var/www
            locale: en_GB
            default_currency: GBP
            db_name: magestead
            base_url: project4.dev
    os: centos65
    server: nginx
