### ISSUE TITLE
Not able to connect to DB via Sequel Pro

### ISSUE THREAD

**Issue by joshuabromero** [richdynamix/magestead#50]
I'm following the guide on the website to try and connect to my database via Sequel Pro. However, I'm prompted for a password using the private key. Am I missing a step somewhere?

---

<img width="816" alt="screen shot 2016-06-02 at 7 45 14 pm" src="https://cloud.githubusercontent.com/assets/16198998/15764651/901e2bf2-28fa-11e6-98bc-1ba1e10be58f.png">

**Comment by richdynamix** [comment]
Hi Joshua,

I am unable to replicate this issue at all. I have just created a new development environment using Magestead and connected to the DB as per the instructions in the docs. From your screenshot I cannot see any issues with your settings.

That being said I have had to update my `known_hosts` file to reflect the SSH key for 127.0.0.1 on port 2222. While this does not ask for a password I wonder if there is anything else on your host machine that could interact with this.

**Comment by richdynamix** [comment]
Is this still an issue?

**Comment by joshuabromero** [comment]
Nope, it was user error. Thanks for following up.

**Comment by Ranjanivraman** [comment]
hi, i am having this same problem now? what was the user error can i please know?
