### ISSUE TITLE
~/.composer/vendor/bin

### ISSUE THREAD

**Issue by theskillwithin** [richdynamix/magestead#58]
~/.composer/vendor/bin

This folder does not exist for me.    Ubuntu 16.04

everything else seemed to work smoothly but this.

**Comment by theskillwithin** [comment]
I looked in /usr/bin  (this appears to be where composer is located)  no sign of magestead or a vendor folder

also looked in /usr/local/bin

**Comment by richdynamix** [comment]
On Ubuntu 16.04 you should find your composer is installed to `/usr/local/bin/composer` if installed globally. If so the `vendor/bin` will fall in here.

The step at adding this to your PATH is only so the magestead executable is found. You may find you don't need to do this step if it was done previously for another package.

Can you run the `magestead` command?

**Comment by bassscape** [comment]
I have installed Magestead but can't run the magestead command.

I assume I have not been able to correctly place the '~/.composer/vendor/bin' directory into my PATH. I don't exactly know what is required to achieve this.

Currently the '~/.composer/vendor/bin' directory currently has a magstead shortcut.

Could you please explain what is required to place the '~/.composer/vendor/bin' directory into my PATH?

**Comment by richdynamix** [comment]
@bassscape Are you on a Mac?
