### ISSUE TITLE
magestead uses incorrect composer config location under Ubuntu 16.04

### ISSUE THREAD

**Issue by btantlinger** [richdynamix/magestead#59]
Under Ubuntu 16.04 the composer config dir is under ~/.config/composer. However, even with this dir set in my PATH, magestead is still looking under ~/.composer.   E.g, after creating a new project I got:

PHP Warning:  file_put_contents(/home/bob/.composer/auth.json): failed to open stream: No such file or directory in /home/bob/.config/composer/vendor/richdynamix/magestead/src/Magestead/Helper/Options.php on line 191

Here is my PATH
/home/bob/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/bob/.config/composer/vendor/bin

So it was trying to create the auth.json in the wrong location.

I had to create a symlink ~/.composer -> ~/.config/composer  for it to work.

**Comment by richdynamix** [comment]
Is this a new location in the recent version of Ubuntu? I was under the impression it was directly in the home folder. I will need to make an update to detect this and update where appropriate.

Feel free to submit a PR if you know what to update :)

**Comment by kasperhelweg** [comment]
Should it be such that the magestead CLI accepts a param for nonstandard .composer locations?

**Comment by richdynamix** [comment]
@kasperhelweg I think you are right. It might be worth having this option available to set this manually and save in a config for future use. My concern is adding too many manual steps for the user. It would be nice if this was automated.
