### ISSUE TITLE
Add parameters to Magento2 cache command

### ISSUE THREAD

**Issue by svossen** [richdynamix/magestead#63]
Is it possible to add parameters to the `cache:clean`and `cache:flush` command? For example, with Magento2 I can use `./bin/magento cache:clean layout` to just clean the layout cache.

I like to clean just specific parts of the cache to make sure the load time after the cache clean is as short as possible.

**Comment by richdynamix** [comment]
Yeah that shouldn't be a problem 👍 I won't have time till tonight to do it but will get it in ASAP.

**Comment by richdynamix** [comment]
@svossen Although I have still to update the docs, cache type params can now be added to the cache commands. i.e. `magestead cache:clean config` The command only expects one param so  to include the comma separated list of types you can incapsulate this in single quotes i.e. `magestead cache:clean 'config layout'`

The params now work on all cache commands.

**Comment by svossen** [comment]
Awesome, thank you!
