### ISSUE TITLE
bash: magestead: command not found

### ISSUE THREAD

**Issue by prabhuchelladurai** [richdynamix/magestead#69]
I have followed all the instructions and installed the composer.

when I give the command 'magestead new My-Project' I got the following output:

```
prabhuchelladurai@Hershel-Harleen ~/Magento $ magestead new My-Project
bash: magestead: command not found
```

what's the flaw and how could it be solved?

Thanks

**Comment by richdynamix** [comment]
Have you set your composer bin directory into your `PATH`?

**Comment by AntonKL** [comment]
Same issue here:

echo $path
`~/.composer/vendor/bin /Users/antonkjorcklinden/.rbenv/shims /usr/local/sbin /usr/local/bin /Users/antonkjorcklinden/.bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin`

**Comment by prabhuchelladurai** [comment]
@richdynamix Yes.. Of course, I did it..

**Comment by richdynamix** [comment]
Which operating system do you have? Can you list the contents of ~/.composer/vendor

**Comment by prabhuchelladurai** [comment]
I am using ROSA Desktop Fresh R7.

But how do I get the contents of ~/.composer/vendor?

**Comment by richdynamix** [comment]
ls-l ~/.composer/vendor

**Comment by prabhuchelladurai** [comment]
The output of the command : ls -l ~/.composer/vendor is

```
prabhuchelladurai@Hershel-Harleen ~/Magento $ ls -l ~/.composer/vendor
ls: cannot access /home/prabhuchelladurai/.composer/vendor: No such file or directory

```

But when I try to execute 'composer global require "richdynamix/magestead" ', I get the following output:

```

prabhuchelladurai@Hershel-Harleen ~/Magento $ composer global update "richdynamix/magestead"
PHP Warning:  Module 'Phar' already loaded in Unknown on line 0
Changed current directory to /home/prabhuchelladurai/.config/composer
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
prabhuchelladurai@Hershel-Harleen ~/Magento $

```

**Comment by richdynamix** [comment]
Unfortunately you are using a flavour of Linux that uses `XDG_CONFIG_HOME`. This is not currently supported with Magestead but should be resolved in future versions.

**Comment by prabhuchelladurai** [comment]
Oh.. Thanks for the clarification. May I know when this could be possibly resolved?
