### ISSUE TITLE
Instalation on a MAC

### ISSUE THREAD

**Issue by inluxc** [richdynamix/magestead#71]
composer global require "richdynamix/magestead"
Changed current directory to /Users/fcarvalhido/.composer
Using version ^2.2 for richdynamix/magestead
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for richdynamix/magestead ^2.2 -> satisfiable by richdynamix/magestead[2.2].
    - Conclusion: remove symfony/console v2.8.6
    - Conclusion: don't install symfony/console v2.8.6
    - richdynamix/magestead 2.2 requires symfony/console ^3.1 -> satisfiable by symfony/console[v3.1.0, v3.1.1, v3.1.2, v3.1.3, v3.1.4].
    - Can only install one of: symfony/console[v3.1.0, v2.8.6].
    - Can only install one of: symfony/console[v3.1.1, v2.8.6].
    - Can only install one of: symfony/console[v3.1.2, v2.8.6].
    - Can only install one of: symfony/console[v3.1.3, v2.8.6].
    - Can only install one of: symfony/console[v3.1.4, v2.8.6].
    - Installation request for symfony/console (locked at v2.8.6) -> satisfiable by symfony/console[v2.8.6].

**Comment by richdynamix** [comment]
Magestead now requires the Symfony console `v3.1+` It would appear you already have `v2.8.6`. To resolve this you must remove the `~/.composer/vendor/symfony/console` directory and re-run the installation. Magestead will install the correct version required.

**Please Note: This may cause issues for other packages that are explicitly using `symfony/console v2.8.6`**

**Comment by sdeboer88** [comment]
I ran into this problem also. Can you give some directions on how to remove the console?

**Comment by richdynamix** [comment]
@inluxc Did this resolve your issues?

**Comment by inluxc** [comment]
Yep, i had an old version installed, i removed it and installed again and everything is right :D
