### ISSUE TITLE
php 7.1

### ISSUE THREAD

**Issue by robmagento** [richdynamix/magestead#93]
You have updated the php version to 7.1 but the composer.json of magento2 does not allow it, resulting in an error when installing. Please check this. Otherwise, all good! :)

**Comment by richdynamix** [comment]
Sorry I don't think I follow. The PHP version hasn't been updated since launch. All boxes remain unchanged.

**Comment by richdynamix** [comment]
Are you sure you haven't updated your local PHP version as this is what would be used during the Magento 2 install.

**Comment by robmagento** [comment]
You might be right :). Sorry, I wasn't aware of this. I thought the "composer install/update" was being run on the VM.

**Comment by richdynamix** [comment]
No problem, I'll close this issue now.
