### ISSUE TITLE
zsh: command not found: magestead

### ISSUE THREAD

**Issue by mnuhell** [richdynamix/magestead#94]
I have installed magested in OSX Capitan but i when run magestead new project 
Shows an error.

`zsh: command not found: magestead`

in `~/.composer/vendor` show this

autoload.php  composer      guzzlehttp    laravel       phpspec       psr           sebastian     webmozart
bin           doctrine      jolicode      phpdocumentor phpunit       richdynamix   symfony

 Thanks so much!!

**Comment by ramsaybell** [comment]
Hi Manuel, is Composer running globally on your system? On OS X:

Edit your bash profile on the terminal:
`vi ~/.bash_profile`

Add this:

`export PATH=~/.composer/vendor/bin:$PATH`

Let me know if you get Magestead running i'm still having issues see here: https://github.com/richdynamix/magestead/issues/87

**Comment by mnuhell** [comment]
Hi, @ramsaybell, thanks for your answer,
it's already working.

**Comment by ramsaybell** [comment]
@mvillagordo Ahh OK, I couldn't get Magestead working so I've built my development environments using Docker.
