### ISSUE TITLE
Install script blocks for ever on windows 10

### ISSUE THREAD

**Issue by RogerKeulen** [richdynamix/magestead#98]
The install script can't install phpspec & behat, also file name doesn't look UTF-8 to me. So, looks like a encoding thing...

Het systeem kan het opgegeven pad niet vinden.
chmod: cannot access **ÔÇÿbin/phpspecÔÇÖ**: No such file or directory
bash: bin/phpspec: No such file or directory
Installing Behat
Het systeem kan het opgegeven pad niet vinden.
chmod: cannot access **ÔÇÿbin/behatÔÇÖ**: No such file or directory
bash: bin/behat: No such file or directory

After that: **Setting Permissions** will take about a hour or so.

**Comment by DonavanHeng** [comment]
Which terminal/shell are you using to execute the install script from? Filenames are encoded in UTF-16, but the output is in ANSI format so it could causes these issues when passing the paths to the bash scripts?

**Comment by RogerKeulen** [comment]
I'm using the `standard` windows command prompt cmd.exe on Windows 10 (home edition).

Thanx in advance.

**Comment by richdynamix** [comment]
Windows is not supported. Please refer to the README
>Mac or Linux (sorry no windows support yet)

Please feel free to submit a PR for windows support.
