### ISSUE TITLE
Windows can't include: "C:\magento2/test-magento3/public/app/etc/env.php"

### ISSUE THREAD

**Issue by RogerKeulen** [richdynamix/magestead#99]
I have the file in: "C:\magento2\test-magento3\public\app\etc\env.php"

Configuring Redis Cache
PHP Warning:  **include(C:\magento2/test-magento3/public/app/etc/env.php): failed to open stream: No such file or directory** in C:\Users\Randy\AppData\Roaming\Composer\vendor\richdynamix\magestead\src\Magestead\Installers\Magento2Project.php on line 174

Warning: **include(C:\magento2/test-magento3/public/app/etc/env.php): failed to open stream: No such file or directory** in C:\Users\Randy\AppData\Roaming\Composer\vendor\richdynamix\magestead\src\Magestead\Installers\Magento2Project.php on line 174
PHP Warning:  include(): Failed opening 'C:\magento2/test-magento3/public/app/etc/env.php' for inclusion (include_path='.;C:\php\pear') in C:\Users\Randy\AppData\Roaming\Composer\vendor\richdynamix\magestead\src\Magestead\Installers\Magento2Project.php on line 174

Warning: include(): Failed opening 'C:\magento2/test-magento3/public/app/etc/env.php' for inclusion (include_path='.;C:\php\pear') in C:\Users\Randy\AppData\Roaming\Composer\vendor\richdynamix\magestead\src\Magestead\Installers\Magento2Project.php on line 174
SUCCESS: Magestead has finished installing Magento 2!

**Comment by richdynamix** [comment]
Windows is not supported. Please refer to the README
>Mac or Linux (sorry no windows support yet)

Please feel free to submit a PR for windows support.
